var stars = [
    {
        "RANK":9,
        "PROPER NAME":"Achernar",
        "GREEK LETTER NAME":"Alpha Eri",
        "CLASS":"B3Vpe",
        "DIST (LY)":140.0,
        "APP MAG":0.46,
        "ABS MAG":-2.7,
        "RAD VEL (km/s)":16.0,
        "VEL (km/s)":26.0,
        "REMARKS":"Rapid rotator, oblate"
    },
    {
        "RANK":13,
        "PROPER NAME":"Acrux A",
        "GREEK LETTER NAME":"Alpha Cru A",
        "CLASS":"B0.5IV",
        "DIST (LY)":325.0,
        "APP MAG":1.3,
        "ABS MAG":-3.9,
        "RAD VEL (km/s)":-11.0,
        "VEL (km/s)":20.0,
        "REMARKS":"Mag uncertain, combined=0.8; by itself ranks 20th"
    },
    {
        "RANK":13,
        "PROPER NAME":"Acrux B",
        "GREEK LETTER NAME":"Alpha Cru B",
        "CLASS":"B1V",
        "DIST (LY)":325.0,
        "APP MAG":1.8,
        "ABS MAG":-3.4,
        "RAD VEL (km/s)":-6.0,
        "VEL (km/s)":18.0,
        "REMARKS":"Mag uncertain, combined=0.8; by itself ranks 30th"
    },
    {
        "RANK":22,
        "PROPER NAME":"Adhara",
        "GREEK LETTER NAME":"Epsilon CMa",
        "CLASS":"B2II",
        "DIST (LY)":405.0,
        "APP MAG":1.5,
        "ABS MAG":-4.0,
        "RAD VEL (km/s)":27.0,
        "VEL (km/s)":27.0,
        "REMARKS":"Brightest star as seen in ultraviolet"
    },
    {
        "RANK":119,
        "PROPER NAME":"Al Dhibain Prior",
        "GREEK LETTER NAME":"Eta Dra",
        "CLASS":"G8III",
        "DIST (LY)":88.0,
        "APP MAG":2.74,
        "ABS MAG":0.59,
        "RAD VEL (km/s)":-14.0,
        "VEL (km/s)":16.0,
        "REMARKS":"9th mag K1 dwarf companion"
    },
    {
        "RANK":114,
        "PROPER NAME":"Al Kab",
        "GREEK LETTER NAME":"Iota Aur",
        "CLASS":"K3II",
        "DIST (LY)":510.0,
        "APP MAG":2.69,
        "ABS MAG":-3.89,
        "RAD VEL (km/s)":18.0,
        "VEL (km/s)":22.0,
        "REMARKS":"X-ray hybrid star"
    },
    {
        "RANK":31,
        "PROPER NAME":"Al Nair",
        "GREEK LETTER NAME":"Alpha Gru",
        "CLASS":"B7IV",
        "DIST (LY)":101.0,
        "APP MAG":1.74,
        "ABS MAG":-0.72,
        "RAD VEL (km/s)":12.0,
        "VEL (km/s)":31.0,
        "REMARKS":"Rapid rotator"
    },
    {
        "RANK":136,
        "PROPER NAME":"Al Niyat",
        "GREEK LETTER NAME":"Tau Sco",
        "CLASS":"B0V",
        "DIST (LY)":430.0,
        "APP MAG":2.82,
        "ABS MAG":-2.97,
        "RAD VEL (km/s)":2.0,
        "VEL (km/s)":15.0,
        "REMARKS":"Slow rotator (or pole-on)"
    },
    {
        "RANK":151,
        "PROPER NAME":"Al Niyat",
        "GREEK LETTER NAME":"Sigma Sco",
        "CLASS":"B2III+O9V",
        "DIST (LY)":735.0,
        "APP MAG":2.89,
        "ABS MAG":-3.38,
        "RAD VEL (km/s)":-0.4,
        "VEL (km/s)":22.0,
        "REMARKS":"Spectroscopic double; 1.3 mag dust absorption"
    },
    {
        "RANK":153,
        "PROPER NAME":"Albaldah",
        "GREEK LETTER NAME":"Pi Sgr",
        "CLASS":"F2II",
        "DIST (LY)":440.0,
        "APP MAG":2.89,
        "ABS MAG":-2.76,
        "RAD VEL (km/s)":-9.8,
        "VEL (km/s)":26.0,
        "REMARKS":"Two close companions"
    },
    {
        "RANK":145,
        "PROPER NAME":"Alcyone",
        "GREEK LETTER NAME":"Eta Tau",
        "CLASS":"B7III",
        "DIST (LY)":430.0,
        "APP MAG":2.87,
        "ABS MAG":-2.83,
        "RAD VEL (km/s)":10.0,
        "VEL (km/s)":31.0,
        "REMARKS":"Brightest of Pleiades \"Be\" (emission) star"
    },
    {
        "RANK":14,
        "PROPER NAME":"Aldebaran",
        "GREEK LETTER NAME":"Alpha Tau",
        "CLASS":"K5III",
        "DIST (LY)":67.0,
        "APP MAG":0.85,
        "ABS MAG":-0.7,
        "RAD VEL (km/s)":54.0,
        "VEL (km/s)":57.0,
        "REMARKS":"In front of Hyades"
    },
    {
        "RANK":86,
        "PROPER NAME":"Alderamin",
        "GREEK LETTER NAME":"Alpha Cep",
        "CLASS":"A7V",
        "DIST (LY)":49.0,
        "APP MAG":2.44,
        "ABS MAG":1.56,
        "RAD VEL (km/s)":-10.0,
        "VEL (km/s)":15.0,
        "REMARKS":"Rapid rotator; unusually active X-ray emitter"
    },
    {
        "RANK":137,
        "PROPER NAME":"Algenib",
        "GREEK LETTER NAME":"Gamma Peg",
        "CLASS":"B2IV",
        "DIST (LY)":333.0,
        "APP MAG":2.83,
        "ABS MAG":-2.21,
        "RAD VEL (km/s)":4.1,
        "VEL (km/s)":6.2,
        "REMARKS":"Beta Cep star; slow rotator (or pole-on)"
    },
    {
        "RANK":164,
        "PROPER NAME":"Algenubi",
        "GREEK LETTER NAME":"Epsilon Leo",
        "CLASS":"G1II",
        "DIST (LY)":250.0,
        "APP MAG":2.98,
        "ABS MAG":-1.45,
        "RAD VEL (km/s)":4.3,
        "VEL (km/s)":17.0,
        "REMARKS":"Cepheid-like pulsations of 0.1 mag"
    },
    {
        "RANK":48,
        "PROPER NAME":"Algieba",
        "GREEK LETTER NAME":"Gamma Leo",
        "CLASS":"K1III+G7III",
        "DIST (LY)":131.0,
        "APP MAG":1.99,
        "ABS MAG":null,
        "RAD VEL (km/s)":-37.0,
        "VEL (km/s)":74.0,
        "REMARKS":"Double, A and B mags 2.29, 3.55, uncertain; abs mags -0.72, 0.54; high velocity"
    },
    {
        "RANK":61,
        "PROPER NAME":"Algol",
        "GREEK LETTER NAME":"Beta Per",
        "CLASS":"B8V",
        "DIST (LY)":93.0,
        "APP MAG":2.12,
        "ABS MAG":-0.15,
        "RAD VEL (km/s)":4.0,
        "VEL (km/s)":4.0,
        "REMARKS":"Classic eclipsing binary"
    },
    {
        "RANK":160,
        "PROPER NAME":"Algorab",
        "GREEK LETTER NAME":"Delta Crv",
        "CLASS":"B9.5V",
        "DIST (LY)":88.0,
        "APP MAG":2.95,
        "ABS MAG":0.8,
        "RAD VEL (km/s)":9.0,
        "VEL (km/s)":33.0,
        "REMARKS":"Attractive binary"
    },
    {
        "RANK":43,
        "PROPER NAME":"Alhena",
        "GREEK LETTER NAME":"Gamma Gem",
        "CLASS":"A0IV",
        "DIST (LY)":105.0,
        "APP MAG":1.93,
        "ABS MAG":-0.6,
        "RAD VEL (km/s)":-12.0,
        "VEL (km/s)":16.0,
        "REMARKS":"Close binary"
    },
    {
        "RANK":32,
        "PROPER NAME":"Alioth",
        "GREEK LETTER NAME":"Epsilon UMa",
        "CLASS":"A0p",
        "DIST (LY)":81.0,
        "APP MAG":1.77,
        "ABS MAG":-0.21,
        "RAD VEL (km/s)":-9.3,
        "VEL (km/s)":16.0,
        "REMARKS":"Alpha-2 CVn magnetic star; Big Dipper; UMa cluster"
    },
    {
        "RANK":38,
        "PROPER NAME":"Alkaid",
        "GREEK LETTER NAME":"Eta UMa",
        "CLASS":"B3V",
        "DIST (LY)":101.0,
        "APP MAG":1.86,
        "ABS MAG":-0.59,
        "RAD VEL (km/s)":-11.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Big Dipper"
    },
    {
        "RANK":167,
        "PROPER NAME":"Almaaz",
        "GREEK LETTER NAME":"Epsilon Aur",
        "CLASS":"F0Iae",
        "DIST (LY)":2000.0,
        "APP MAG":2.99,
        "ABS MAG":-6.9,
        "RAD VEL (km/s)":-2.5,
        "VEL (km/s)":7.0,
        "REMARKS":"Weird eclipsing binary, 27 yr period; 1.0 mag interstellar abs"
    },
    {
        "RANK":63,
        "PROPER NAME":"Almach",
        "GREEK LETTER NAME":"Gamma And",
        "CLASS":"K3II+(B8V+A0V)",
        "DIST (LY)":355.0,
        "APP MAG":2.16,
        "ABS MAG":null,
        "RAD VEL (km/s)":-12.0,
        "VEL (km/s)":36.0,
        "REMARKS":"Classic vis. binary mags 2.26, 4.84; B also double, mags 5.1, 6.3; brighter spect binary; abs mag primary -2.92"
    },
    {
        "RANK":168,
        "PROPER NAME":"Alnasl",
        "GREEK LETTER NAME":"Gamma-2 Sgr",
        "CLASS":"K0III",
        "DIST (LY)":96.0,
        "APP MAG":2.99,
        "ABS MAG":0.64,
        "RAD VEL (km/s)":22.0,
        "VEL (km/s)":34.0,
        "REMARKS":"Gateway to Cepheid W Sgr"
    },
    {
        "RANK":29,
        "PROPER NAME":"Alnilam",
        "GREEK LETTER NAME":"Epsilon Ori",
        "CLASS":"B0Ia",
        "DIST (LY)":1340.0,
        "APP MAG":1.7,
        "ABS MAG":-6.6,
        "RAD VEL (km/s)":26.0,
        "VEL (km/s)":26.0,
        "REMARKS":"Central Belt star"
    },
    {
        "RANK":30,
        "PROPER NAME":"Alnitak",
        "GREEK LETTER NAME":"Zeta Ori",
        "CLASS":"O9.5Ibe+B0III",
        "DIST (LY)":815.0,
        "APP MAG":1.74,
        "ABS MAG":-5.5,
        "RAD VEL (km/s)":16.0,
        "VEL (km/s)":17.0,
        "REMARKS":"Eastern Belt star; visual binary"
    },
    {
        "RANK":159,
        "PROPER NAME":"Alpha Ara",
        "GREEK LETTER NAME":"Alpha Ara",
        "CLASS":"B2Ve",
        "DIST (LY)":267.0,
        "APP MAG":2.95,
        "ABS MAG":-1.94,
        "RAD VEL (km/s)":0.0,
        "VEL (km/s)":29.0,
        "REMARKS":"B-emission shell star"
    },
    {
        "RANK":143,
        "PROPER NAME":"Alpha Hyi",
        "GREEK LETTER NAME":"Alpha Hyi",
        "CLASS":"F0V",
        "DIST (LY)":71.0,
        "APP MAG":2.86,
        "ABS MAG":1.16,
        "RAD VEL (km/s)":7.0,
        "VEL (km/s)":28.0,
        "REMARKS":"South pole star 2900 BC"
    },
    {
        "RANK":112,
        "PROPER NAME":"Alpha Mus",
        "GREEK LETTER NAME":"Alpha Mus",
        "CLASS":"B2IV-V",
        "DIST (LY)":305.0,
        "APP MAG":2.69,
        "ABS MAG":-2.3,
        "RAD VEL (km/s)":13.0,
        "VEL (km/s)":23.0,
        "REMARKS":"Beta Cep variable"
    },
    {
        "RANK":144,
        "PROPER NAME":"Alpha Tuc",
        "GREEK LETTER NAME":"Alpha Tuc",
        "CLASS":"K3III",
        "DIST (LY)":199.0,
        "APP MAG":2.86,
        "ABS MAG":-1.06,
        "RAD VEL (km/s)":42.0,
        "VEL (km/s)":48.0,
        "REMARKS":"Spectroscopic double"
    },
    {
        "RANK":47,
        "PROPER NAME":"Alphard",
        "GREEK LETTER NAME":"Alpha Hya",
        "CLASS":"K3II-III",
        "DIST (LY)":177.0,
        "APP MAG":1.98,
        "ABS MAG":-1.7,
        "RAD VEL (km/s)":-4.0,
        "VEL (km/s)":10.0,
        "REMARKS":"Barium star"
    },
    {
        "RANK":68,
        "PROPER NAME":"Alphecca",
        "GREEK LETTER NAME":"Alpha CrB",
        "CLASS":"A0V",
        "DIST (LY)":75.0,
        "APP MAG":2.23,
        "ABS MAG":0.43,
        "RAD VEL (km/s)":1.7,
        "VEL (km/s)":16.0,
        "REMARKS":"\"Gemma\"; elipsing binary, G5 companion"
    },
    {
        "RANK":54,
        "PROPER NAME":"Alpheratz",
        "GREEK LETTER NAME":"Alpha And",
        "CLASS":"B8IVp",
        "DIST (LY)":97.0,
        "APP MAG":2.06,
        "ABS MAG":-0.31,
        "RAD VEL (km/s)":-12.0,
        "VEL (km/s)":30.0,
        "REMARKS":"Mercury-manganese star; spect binary"
    },
    {
        "RANK":12,
        "PROPER NAME":"Altair",
        "GREEK LETTER NAME":"Alpha Aql",
        "CLASS":"A7V",
        "DIST (LY)":16.7,
        "APP MAG":0.77,
        "ABS MAG":2.22,
        "RAD VEL (km/s)":-26.0,
        "VEL (km/s)":30.0,
        "REMARKS":"Rapid rotator, oblate"
    },
    {
        "RANK":87,
        "PROPER NAME":"Aludra",
        "GREEK LETTER NAME":"Eta CMa",
        "CLASS":"B5Ia",
        "DIST (LY)":3200.0,
        "APP MAG":2.45,
        "ABS MAG":-7.5,
        "RAD VEL (km/s)":41.0,
        "VEL (km/s)":54.0,
        "REMARKS":"Distance poor; strong wind"
    },
    {
        "RANK":80,
        "PROPER NAME":"Ankaa",
        "GREEK LETTER NAME":"Alpha Phe",
        "CLASS":"K0III",
        "DIST (LY)":77.0,
        "APP MAG":2.39,
        "ABS MAG":0.52,
        "RAD VEL (km/s)":75.0,
        "VEL (km/s)":88.0,
        "REMARKS":"High velocity; low-mass companion"
    },
    {
        "RANK":15,
        "PROPER NAME":"Antares",
        "GREEK LETTER NAME":"Alpha Sco",
        "CLASS":"M1.5Ib",
        "DIST (LY)":550.0,
        "APP MAG":0.96,
        "ABS MAG":-5.7,
        "RAD VEL (km/s)":-3.0,
        "VEL (km/s)":35.0,
        "REMARKS":"Semi-reg variable by a few tenths of a mag; 0.5 mag dust abs."
    },
    {
        "RANK":4,
        "PROPER NAME":"Arcturus",
        "GREEK LETTER NAME":"Alpha Boo",
        "CLASS":"K1.5III",
        "DIST (LY)":37.0,
        "APP MAG":-0.04,
        "ABS MAG":-0.3,
        "RAD VEL (km/s)":-5.0,
        "VEL (km/s)":122.0,
        "REMARKS":"High velocity"
    },
    {
        "RANK":97,
        "PROPER NAME":"Arneb",
        "GREEK LETTER NAME":"Alpha Lep",
        "CLASS":"F0Ib",
        "DIST (LY)":1300.0,
        "APP MAG":2.58,
        "ABS MAG":-5.56,
        "RAD VEL (km/s)":24.0,
        "VEL (km/s)":25.0,
        "REMARKS":"Nitrogen-enhanced; state of rapid evolution"
    },
    {
        "RANK":102,
        "PROPER NAME":"Ascella",
        "GREEK LETTER NAME":"Zeta Sgr",
        "CLASS":"A2III+A4IV",
        "DIST (LY)":89.0,
        "APP MAG":2.61,
        "ABS MAG":null,
        "RAD VEL (km/s)":22.0,
        "VEL (km/s)":22.0,
        "REMARKS":"Close binary, mags 3.26, 3.47, abs mags 1.08, 1.29, 21 yr orbit."
    },
    {
        "RANK":72,
        "PROPER NAME":"Aspidiske",
        "GREEK LETTER NAME":"Iota Car",
        "CLASS":"A8Ib",
        "DIST (LY)":690.0,
        "APP MAG":2.25,
        "ABS MAG":-4.42,
        "RAD VEL (km/s)":13.0,
        "VEL (km/s)":27.0,
        "REMARKS":"Other names: Scutulum, Tureis; False Cross"
    },
    {
        "RANK":42,
        "PROPER NAME":"Atria",
        "GREEK LETTER NAME":"Alpha TrA",
        "CLASS":"K3II-III",
        "DIST (LY)":415.0,
        "APP MAG":1.92,
        "ABS MAG":-3.61,
        "RAD VEL (km/s)":-3.0,
        "VEL (km/s)":23.0,
        "REMARKS":"Hybrid star; barium star; with Miaplacidus, one of two bright stars near SCP"
    },
    {
        "RANK":39,
        "PROPER NAME":"Avior",
        "GREEK LETTER NAME":"Epsilon Car",
        "CLASS":"K3III+B2V",
        "DIST (LY)":630.0,
        "APP MAG":1.86,
        "ABS MAG":-4.6,
        "RAD VEL (km/s)":12.0,
        "VEL (km/s)":34.0,
        "REMARKS":"Unresolved binary; False Cross"
    },
    {
        "RANK":26,
        "PROPER NAME":"Bellatrix",
        "GREEK LETTER NAME":"Gamma Ori",
        "CLASS":"B2III",
        "DIST (LY)":245.0,
        "APP MAG":1.64,
        "ABS MAG":-2.72,
        "RAD VEL (km/s)":18.0,
        "VEL (km/s)":19.0,
        "REMARKS":"Slightly variable"
    },
    {
        "RANK":142,
        "PROPER NAME":"Beta Ara",
        "GREEK LETTER NAME":"Beta Ara",
        "CLASS":"K3Ib-II",
        "DIST (LY)":603.0,
        "APP MAG":2.85,
        "ABS MAG":-3.48,
        "RAD VEL (km/s)":-0.4,
        "VEL (km/s)":23.0,
        "REMARKS":"Super metal-rich"
    },
    {
        "RANK":60,
        "PROPER NAME":"Beta Gru",
        "GREEK LETTER NAME":"Beta Gru",
        "CLASS":"M5III",
        "DIST (LY)":170.0,
        "APP MAG":2.1,
        "ABS MAG":-1.49,
        "RAD VEL (km/s)":1.6,
        "VEL (km/s)":34.0,
        "REMARKS":"Irregular variable"
    },
    {
        "RANK":131,
        "PROPER NAME":"Beta Hyi",
        "GREEK LETTER NAME":"Beta Hyi",
        "CLASS":"G2IV",
        "DIST (LY)":24.4,
        "APP MAG":2.8,
        "ABS MAG":3.43,
        "RAD VEL (km/s)":23.0,
        "VEL (km/s)":83.0,
        "REMARKS":"High velocity; south pole star 150 BC"
    },
    {
        "RANK":108,
        "PROPER NAME":"Beta Lup",
        "GREEK LETTER NAME":"Beta Lup",
        "CLASS":"B2III",
        "DIST (LY)":524.0,
        "APP MAG":2.68,
        "ABS MAG":-3.41,
        "RAD VEL (km/s)":6.2,
        "VEL (km/s)":39.0,
        "REMARKS":"Beta Cephei variable"
    },
    {
        "RANK":141,
        "PROPER NAME":"Beta TrA",
        "GREEK LETTER NAME":"Beta TrA",
        "CLASS":"F2III",
        "DIST (LY)":40.0,
        "APP MAG":2.85,
        "ABS MAG":2.4,
        "RAD VEL (km/s)":0.4,
        "VEL (km/s)":26.0,
        "REMARKS":"Really a dwarf"
    },
    {
        "RANK":170,
        "PROPER NAME":"Beta Tri",
        "GREEK LETTER NAME":"Beta Tri",
        "CLASS":"A5III",
        "DIST (LY)":124.0,
        "APP MAG":3.0,
        "ABS MAG":0.09,
        "RAD VEL (km/s)":9.9,
        "VEL (km/s)":30.0,
        "REMARKS":"Really a dwarf; close sunlike companion"
    },
    {
        "RANK":11,
        "PROPER NAME":"Betelgeuse",
        "GREEK LETTER NAME":"Alpha Ori",
        "CLASS":"M2Iab",
        "DIST (LY)":570.0,
        "APP MAG":0.7,
        "ABS MAG":-5.5,
        "RAD VEL (km/s)":21.0,
        "VEL (km/s)":33.0,
        "REMARKS":"Semi-regular variable, mag between 0.2 and 1.5l; distance might be high as 640 ly"
    },
    {
        "RANK":2,
        "PROPER NAME":"Canopus",
        "GREEK LETTER NAME":"Alpha Car",
        "CLASS":"F0II",
        "DIST (LY)":309.0,
        "APP MAG":-0.72,
        "ABS MAG":-5.6,
        "RAD VEL (km/s)":21.0,
        "VEL (km/s)":25.0,
        "REMARKS":"X-rays from hot corona; may become neon white dwarf"
    },
    {
        "RANK":6,
        "PROPER NAME":"Capella",
        "GREEK LETTER NAME":"Alpha Aur",
        "CLASS":"G8III+G0III",
        "DIST (LY)":43.0,
        "APP MAG":0.08,
        "ABS MAG":-0.51,
        "RAD VEL (km/s)":30.0,
        "VEL (km/s)":40.0,
        "REMARKS":"Close binary, mags. 0.76 and 0.91"
    },
    {
        "RANK":73,
        "PROPER NAME":"Caph",
        "GREEK LETTER NAME":"Beta Cas",
        "CLASS":"F2III-IV",
        "DIST (LY)":54.0,
        "APP MAG":2.27,
        "ABS MAG":1.16,
        "RAD VEL (km/s)":11.0,
        "VEL (km/s)":44.0,
        "REMARKS":"Delta Sct variable; close companion"
    },
    {
        "RANK":23,
        "PROPER NAME":"Castor",
        "GREEK LETTER NAME":"Alpha Gem",
        "CLASS":"A1V+A5Vm",
        "DIST (LY)":51.0,
        "APP MAG":1.58,
        "ABS MAG":0.61,
        "RAD VEL (km/s)":6.0,
        "VEL (km/s)":16.0,
        "REMARKS":"Quadruple, with binary C (M1 Ve) sextuple; A and B magnitudes 1.93, 2.97; B class A2?"
    },
    {
        "RANK":126,
        "PROPER NAME":"Cebalrai",
        "GREEK LETTER NAME":"Beta Oph",
        "CLASS":"K2III",
        "DIST (LY)":82.0,
        "APP MAG":2.77,
        "ABS MAG":0.77,
        "RAD VEL (km/s)":-12.0,
        "VEL (km/s)":20.0,
        "REMARKS":"Subtle pulsations; spotted rotator; guide to Poniatowski's Bull"
    },
    {
        "RANK":132,
        "PROPER NAME":"Cor Caroli",
        "GREEK LETTER NAME":"Alpha CVn",
        "CLASS":"Aop",
        "DIST (LY)":110.0,
        "APP MAG":2.81,
        "ABS MAG":0.17,
        "RAD VEL (km/s)":-3.3,
        "VEL (km/s)":39.0,
        "REMARKS":"Double, mags=2.9, 5.6, abs mags=0.26, 2.96; Alpha-2 magnetic"
    },
    {
        "RANK":128,
        "PROPER NAME":"Cursa",
        "GREEK LETTER NAME":"Beta Eri",
        "CLASS":"A3III",
        "DIST (LY)":89.0,
        "APP MAG":2.79,
        "ABS MAG":0.61,
        "RAD VEL (km/s)":-9.2,
        "VEL (km/s)":17.0,
        "REMARKS":"Possible large flashes"
    },
    {
        "RANK":100,
        "PROPER NAME":"Delta Cen",
        "GREEK LETTER NAME":"Delta Cen",
        "CLASS":"B2IV",
        "DIST (LY)":395.0,
        "APP MAG":2.6,
        "ABS MAG":-3.2,
        "RAD VEL (km/s)":11.0,
        "VEL (km/s)":29.0,
        "REMARKS":"\"Be\" emission (shell) star"
    },
    {
        "RANK":130,
        "PROPER NAME":"Delta Cru",
        "GREEK LETTER NAME":"Delta Cru",
        "CLASS":"B2IV",
        "DIST (LY)":364.0,
        "APP MAG":2.8,
        "ABS MAG":-2.47,
        "RAD VEL (km/s)":22.0,
        "VEL (km/s)":30.0,
        "REMARKS":"Fast rotator; Beta Cephei star"
    },
    {
        "RANK":146,
        "PROPER NAME":"Delta Cyg",
        "GREEK LETTER NAME":"Delta Cyg",
        "CLASS":"B9.5IV+F1V",
        "DIST (LY)":171.0,
        "APP MAG":2.87,
        "ABS MAG":-0.74,
        "RAD VEL (km/s)":-20.0,
        "VEL (km/s)":26.0,
        "REMARKS":"Double star, mags 2.9, 6.3, combined uncertain"
    },
    {
        "RANK":45,
        "PROPER NAME":"Delta Vel",
        "GREEK LETTER NAME":"Delta Vel",
        "CLASS":"A1V",
        "DIST (LY)":80.0,
        "APP MAG":1.96,
        "ABS MAG":0.02,
        "RAD VEL (km/s)":2.0,
        "VEL (km/s)":13.0,
        "REMARKS":"Multiple star; S. pole star in 9000 AD; False Cross"
    },
    {
        "RANK":19,
        "PROPER NAME":"Deneb",
        "GREEK LETTER NAME":"Alpha Cyg",
        "CLASS":"A2Ia",
        "DIST (LY)":1425.0,
        "APP MAG":1.25,
        "ABS MAG":-7.09,
        "RAD VEL (km/s)":-5.0,
        "VEL (km/s)":6.0,
        "REMARKS":"One of the brightest class A supergiants; spectrum variable"
    },
    {
        "RANK":147,
        "PROPER NAME":"Deneb Algedi",
        "GREEK LETTER NAME":"Delta Cap",
        "CLASS":"AmV",
        "DIST (LY)":39.0,
        "APP MAG":2.87,
        "ABS MAG":2.51,
        "RAD VEL (km/s)":-6.3,
        "VEL (km/s)":23.0,
        "REMARKS":"Eclipsing binary; metallic-line Delta Scuti star"
    },
    {
        "RANK":52,
        "PROPER NAME":"Deneb Kaitos",
        "GREEK LETTER NAME":"Beta Cet",
        "CLASS":"K0III",
        "DIST (LY)":96.0,
        "APP MAG":2.04,
        "ABS MAG":-0.3,
        "RAD VEL (km/s)":13.0,
        "VEL (km/s)":35.0,
        "REMARKS":"Bright X-ray source"
    },
    {
        "RANK":166,
        "PROPER NAME":"Deneb Okab Aus",
        "GREEK LETTER NAME":"Zeta Aql",
        "CLASS":"A0V",
        "DIST (LY)":83.0,
        "APP MAG":2.99,
        "ABS MAG":0.96,
        "RAD VEL (km/s)":-25.0,
        "VEL (km/s)":25.0,
        "REMARKS":"Very rapid rotation"
    },
    {
        "RANK":62,
        "PROPER NAME":"Denebola",
        "GREEK LETTER NAME":"Beta Leo",
        "CLASS":"A3V",
        "DIST (LY)":36.0,
        "APP MAG":2.14,
        "ABS MAG":1.92,
        "RAD VEL (km/s)":-0.2,
        "VEL (km/s)":27.0,
        "REMARKS":"Vega system, circumstellar dust"
    },
    {
        "RANK":78,
        "PROPER NAME":"Dschubba",
        "GREEK LETTER NAME":"Delta Sco",
        "CLASS":"B0.3IV",
        "DIST (LY)":400.0,
        "APP MAG":2.32,
        "ABS MAG":-3.6,
        "RAD VEL (km/s)":-7.0,
        "VEL (km/s)":23.0,
        "REMARKS":"\"Be\" star now in outburst"
    },
    {
        "RANK":34,
        "PROPER NAME":"Dubhe",
        "GREEK LETTER NAME":"Alpha UMa",
        "CLASS":"K0III",
        "DIST (LY)":124.0,
        "APP MAG":1.79,
        "ABS MAG":-1.1,
        "RAD VEL (km/s)":-9.0,
        "VEL (km/s)":27.0,
        "REMARKS":"F0V companion; Big Dipper; UMa cluster"
    },
    {
        "RANK":27,
        "PROPER NAME":"Elnath",
        "GREEK LETTER NAME":"Beta Tau",
        "CLASS":"B7III",
        "DIST (LY)":130.0,
        "APP MAG":1.65,
        "ABS MAG":-1.37,
        "RAD VEL (km/s)":9.0,
        "VEL (km/s)":35.0,
        "REMARKS":"Also Gamma Aurigae"
    },
    {
        "RANK":70,
        "PROPER NAME":"Eltanin",
        "GREEK LETTER NAME":"Gamma Dra",
        "CLASS":"K5III",
        "DIST (LY)":148.0,
        "APP MAG":2.23,
        "ABS MAG":-1.05,
        "RAD VEL (km/s)":-28.0,
        "VEL (km/s)":28.0,
        "REMARKS":"\"Zenith star,\" from which aberration of starlight found"
    },
    {
        "RANK":81,
        "PROPER NAME":"Enif",
        "GREEK LETTER NAME":"Epsilon Peg",
        "CLASS":"K2Ib",
        "DIST (LY)":670.0,
        "APP MAG":2.39,
        "ABS MAG":-4.18,
        "RAD VEL (km/s)":5.0,
        "VEL (km/s)":30.0,
        "REMARKS":"Giant flare?"
    },
    {
        "RANK":75,
        "PROPER NAME":"Eps Cen",
        "GREEK LETTER NAME":"Epsilon Cen",
        "CLASS":"B1III",
        "DIST (LY)":375.0,
        "APP MAG":2.3,
        "ABS MAG":-3.13,
        "RAD VEL (km/s)":3.0,
        "VEL (km/s)":11.0,
        "REMARKS":"Beta Cep variable; faint companion"
    },
    {
        "RANK":74,
        "PROPER NAME":"Eps Sco",
        "GREEK LETTER NAME":"Epsilon Sco",
        "CLASS":"K2.5III",
        "DIST (LY)":65.0,
        "APP MAG":2.29,
        "ABS MAG":0.77,
        "RAD VEL (km/s)":-2.5,
        "VEL (km/s)":63.0,
        "REMARKS":"High velocity"
    },
    {
        "RANK":149,
        "PROPER NAME":"Epsilon Per",
        "GREEK LETTER NAME":"Epsilon Per",
        "CLASS":"B0.5V",
        "DIST (LY)":538.0,
        "APP MAG":2.89,
        "ABS MAG":-3.58,
        "RAD VEL (km/s)":1.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Beta Cephei star; 0.38 mag dust absorption"
    },
    {
        "RANK":77,
        "PROPER NAME":"Eta Cen",
        "GREEK LETTER NAME":"Eta Cen",
        "CLASS":"B1.5Ve",
        "DIST (LY)":310.0,
        "APP MAG":2.31,
        "ABS MAG":-2.73,
        "RAD VEL (km/s)":-0.2,
        "VEL (km/s)":22.0,
        "REMARKS":"Rapid rotator; \"Be\" star with surrounding disk"
    },
    {
        "RANK":18,
        "PROPER NAME":"Fomalhaut",
        "GREEK LETTER NAME":"Alpha PsA",
        "CLASS":"A3V",
        "DIST (LY)":25.0,
        "APP MAG":1.16,
        "ABS MAG":1.73,
        "RAD VEL (km/s)":7.0,
        "VEL (km/s)":15.0,
        "REMARKS":"Dusty circumstellar disk and a planet"
    },
    {
        "RANK":24,
        "PROPER NAME":"Gacrux",
        "GREEK LETTER NAME":"Gamma Cru",
        "CLASS":"M3.5III",
        "DIST (LY)":88.0,
        "APP MAG":1.63,
        "ABS MAG":-0.52,
        "RAD VEL (km/s)":21.0,
        "VEL (km/s)":40.0,
        "REMARKS":"Mild barium star"
    },
    {
        "RANK":89,
        "PROPER NAME":"Gamma Cas",
        "GREEK LETTER NAME":"Gamma Cas",
        "CLASS":"B0IVpe",
        "DIST (LY)":549.0,
        "APP MAG":2.47,
        "ABS MAG":-4.0,
        "RAD VEL (km/s)":-7.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Classic \"Be\" (emission) star; unpredictably variable; can be much brighter"
    },
    {
        "RANK":171,
        "PROPER NAME":"Gamma Hydrae",
        "GREEK LETTER NAME":"Gamma Hya",
        "CLASS":"G8III",
        "DIST (LY)":132.0,
        "APP MAG":3.0,
        "ABS MAG":-0.04,
        "RAD VEL (km/s)":-5.4,
        "VEL (km/s)":16.0,
        "REMARKS":"A star in transition"
    },
    {
        "RANK":127,
        "PROPER NAME":"Gamma Lup",
        "GREEK LETTER NAME":"Gamma Lup",
        "CLASS":"B2IV",
        "DIST (LY)":421.0,
        "APP MAG":2.78,
        "ABS MAG":-3.05,
        "RAD VEL (km/s)":2.3,
        "VEL (km/s)":22.0,
        "REMARKS":"Spect. double, with B4V, 0.19 mag int. abs. 0.19 mag"
    },
    {
        "RANK":156,
        "PROPER NAME":"Gamma Per",
        "GREEK LETTER NAME":"Gamma Per",
        "CLASS":"G8III+A2V",
        "DIST (LY)":218.0,
        "APP MAG":2.93,
        "ABS MAG":-1.2,
        "RAD VEL (km/s)":2.5,
        "VEL (km/s)":2.8,
        "REMARKS":"Second brightest eclipsing binary, partial, 14.6 yr period"
    },
    {
        "RANK":152,
        "PROPER NAME":"Gamma TrA",
        "GREEK LETTER NAME":"Gamma TrA",
        "CLASS":"A1V",
        "DIST (LY)":183.0,
        "APP MAG":2.89,
        "ABS MAG":-0.85,
        "RAD VEL (km/s)":-3.0,
        "VEL (km/s)":20.0,
        "REMARKS":"Chemically peculiar; rapid rotator"
    },
    {
        "RANK":98,
        "PROPER NAME":"Gienah",
        "GREEK LETTER NAME":"Gamma Crv",
        "CLASS":"B8IIIpHgMn",
        "DIST (LY)":165.0,
        "APP MAG":2.59,
        "ABS MAG":-0.93,
        "RAD VEL (km/s)":-4.2,
        "VEL (km/s)":39.0,
        "REMARKS":"Mercury-manganese star"
    },
    {
        "RANK":88,
        "PROPER NAME":"Gienah Cygni",
        "GREEK LETTER NAME":"Epsilon Cyg",
        "CLASS":"K0III",
        "DIST (LY)":72.0,
        "APP MAG":2.46,
        "ABS MAG":0.74,
        "RAD VEL (km/s)":-11.0,
        "VEL (km/s)":52.0,
        "REMARKS":"Distant dim companion"
    },
    {
        "RANK":40,
        "PROPER NAME":"Girtab",
        "GREEK LETTER NAME":"Theta Sco",
        "CLASS":"F1II",
        "DIST (LY)":272.0,
        "APP MAG":1.87,
        "ABS MAG":-2.73,
        "RAD VEL (km/s)":1.0,
        "VEL (km/s)":3.0,
        "REMARKS":"Scorpius's southern limit"
    },
    {
        "RANK":154,
        "PROPER NAME":"Gomeisa",
        "GREEK LETTER NAME":"Beta CMi",
        "CLASS":"B8Ve",
        "DIST (LY)":170.0,
        "APP MAG":2.9,
        "ABS MAG":-0.69,
        "RAD VEL (km/s)":22.0,
        "VEL (km/s)":27.0,
        "REMARKS":"\"Be\" (emission) star"
    },
    {
        "RANK":91,
        "PROPER NAME":"Graffias",
        "GREEK LETTER NAME":"Beta Sco",
        "CLASS":"B1V+B2V",
        "DIST (LY)":530.0,
        "APP MAG":2.5,
        "ABS MAG":null,
        "RAD VEL (km/s)":-2.0,
        "VEL (km/s)":23.0,
        "REMARKS":"Binary, mags 2.62, 4.92; abs mags -4.10, -1.80, 0.7 mag interstellar abs"
    },
    {
        "RANK":10,
        "PROPER NAME":"Hadar",
        "GREEK LETTER NAME":"Beta Cen",
        "CLASS":"B1III",
        "DIST (LY)":392.0,
        "APP MAG":0.61,
        "ABS MAG":-4.81,
        "RAD VEL (km/s)":6.0,
        "VEL (km/s)":33.0,
        "REMARKS":"Close binary twins with more distant companion; Beta Cephei variable"
    },
    {
        "RANK":49,
        "PROPER NAME":"Hamal",
        "GREEK LETTER NAME":"Alpha Ari",
        "CLASS":"K2III",
        "DIST (LY)":66.0,
        "APP MAG":2.0,
        "ABS MAG":0.47,
        "RAD VEL (km/s)":-14.0,
        "VEL (km/s)":27.0,
        "REMARKS":"Somewhat low in metals"
    },
    {
        "RANK":121,
        "PROPER NAME":"Iota Cen",
        "GREEK LETTER NAME":"Iota Cen",
        "CLASS":"A2V",
        "DIST (LY)":59.0,
        "APP MAG":2.75,
        "ABS MAG":1.48,
        "RAD VEL (km/s)":0.1,
        "VEL (km/s)":30.0,
        "REMARKS":"Measured as bright as 2.70; dusty disk"
    },
    {
        "RANK":99,
        "PROPER NAME":"Izar",
        "GREEK LETTER NAME":"Epsilon Boo",
        "CLASS":"K0II-III+A2V",
        "DIST (LY)":205.0,
        "APP MAG":2.59,
        "ABS MAG":null,
        "RAD VEL (km/s)":-17.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Double, abs mags -1.3, 1.1; distance, vis mags uncertain"
    },
    {
        "RANK":76,
        "PROPER NAME":"Kakkab",
        "GREEK LETTER NAME":"Alpha Lup",
        "CLASS":"B1.5III",
        "DIST (LY)":550.0,
        "APP MAG":2.3,
        "ABS MAG":-4.02,
        "RAD VEL (km/s)":5.0,
        "VEL (km/s)":26.0,
        "REMARKS":"Beta Cep variable"
    },
    {
        "RANK":82,
        "PROPER NAME":"Kappa Sco",
        "GREEK LETTER NAME":"Kappa Sco",
        "CLASS":"B1.5III",
        "DIST (LY)":450.0,
        "APP MAG":2.41,
        "ABS MAG":-3.4,
        "RAD VEL (km/s)":-14.0,
        "VEL (km/s)":22.0,
        "REMARKS":"Close binary; Beta Cep variable"
    },
    {
        "RANK":37,
        "PROPER NAME":"Kaus Australis",
        "GREEK LETTER NAME":"Epsilon Sgr",
        "CLASS":"B9.5III",
        "DIST (LY)":143.0,
        "APP MAG":1.85,
        "ABS MAG":-1.38,
        "RAD VEL (km/s)":-15.0,
        "VEL (km/s)":31.0,
        "REMARKS":"Possible circumstellar shell"
    },
    {
        "RANK":135,
        "PROPER NAME":"Kaus Borealis",
        "GREEK LETTER NAME":"Lambda Sgr",
        "CLASS":"K1III",
        "DIST (LY)":77.0,
        "APP MAG":2.81,
        "ABS MAG":0.94,
        "RAD VEL (km/s)":42.0,
        "VEL (km/s)":48.0,
        "REMARKS":"Modest X-ray source"
    },
    {
        "RANK":116,
        "PROPER NAME":"Kaus Media",
        "GREEK LETTER NAME":"Delta Sgr",
        "CLASS":"K3III",
        "DIST (LY)":305.0,
        "APP MAG":2.7,
        "ABS MAG":-2.16,
        "RAD VEL (km/s)":-20.0,
        "VEL (km/s)":29.0,
        "REMARKS":"Possible conmpanion(s); weak barium star"
    },
    {
        "RANK":59,
        "PROPER NAME":"Kochab",
        "GREEK LETTER NAME":"Beta UMi",
        "CLASS":"K4III",
        "DIST (LY)":126.0,
        "APP MAG":2.08,
        "ABS MAG":-0.86,
        "RAD VEL (km/s)":17.0,
        "VEL (km/s)":18.0,
        "REMARKS":"With Pherkad, a Guardian of the Pole; marginal barium star"
    },
    {
        "RANK":125,
        "PROPER NAME":"Kornephoros",
        "GREEK LETTER NAME":"Beta Her",
        "CLASS":"G7III",
        "DIST (LY)":148.0,
        "APP MAG":2.77,
        "ABS MAG":-0.51,
        "RAD VEL (km/s)":-26.0,
        "VEL (km/s)":33.0,
        "REMARKS":"X-ray emission; spect. binary"
    },
    {
        "RANK":106,
        "PROPER NAME":"Kraz",
        "GREEK LETTER NAME":"Beta Crv",
        "CLASS":"G5II",
        "DIST (LY)":140.0,
        "APP MAG":2.65,
        "ABS MAG":-0.51,
        "RAD VEL (km/s)":-7.6,
        "VEL (km/s)":14.0,
        "REMARKS":"Possible weak barium star"
    },
    {
        "RANK":111,
        "PROPER NAME":"Lesath",
        "GREEK LETTER NAME":"Upsilon Sco",
        "CLASS":"B2IV",
        "DIST (LY)":520.0,
        "APP MAG":2.69,
        "ABS MAG":-3.38,
        "RAD VEL (km/s)":8.0,
        "VEL (km/s)":24.0,
        "REMARKS":"Possible \"Be\" emisison star"
    },
    {
        "RANK":90,
        "PROPER NAME":"Markab",
        "GREEK LETTER NAME":"Alpha Peg",
        "CLASS":"B9V",
        "DIST (LY)":140.0,
        "APP MAG":2.49,
        "ABS MAG":-0.67,
        "RAD VEL (km/s)":-3.5,
        "VEL (km/s)":16.0,
        "REMARKS":"Known for \"normality\"; also classed as giant"
    },
    {
        "RANK":92,
        "PROPER NAME":"Markeb",
        "GREEK LETTER NAME":"Kappa Vel",
        "CLASS":"B2IV-V",
        "DIST (LY)":540.0,
        "APP MAG":2.5,
        "ABS MAG":-3.78,
        "RAD VEL (km/s)":22.0,
        "VEL (km/s)":25.0,
        "REMARKS":"Spect binary; False Cross"
    },
    {
        "RANK":158,
        "PROPER NAME":"Matar",
        "GREEK LETTER NAME":"Eta Peg",
        "CLASS":"G2II-III",
        "DIST (LY)":215.0,
        "APP MAG":2.94,
        "ABS MAG":-1.15,
        "RAD VEL (km/s)":4.3,
        "VEL (km/s)":10.0,
        "REMARKS":"Quadruple star"
    },
    {
        "RANK":165,
        "PROPER NAME":"Mebsuta",
        "GREEK LETTER NAME":"Epsilon Gem",
        "CLASS":"G8Ib",
        "DIST (LY)":900.0,
        "APP MAG":2.98,
        "ABS MAG":-4.23,
        "RAD VEL (km/s)":9.9,
        "VEL (km/s)":21.0,
        "REMARKS":"Frequently occulted by Moon; possible companion"
    },
    {
        "RANK":41,
        "PROPER NAME":"Menkalinan",
        "GREEK LETTER NAME":"Beta Aur",
        "CLASS":"A2IV",
        "DIST (LY)":82.0,
        "APP MAG":1.9,
        "ABS MAG":-0.1,
        "RAD VEL (km/s)":-18.0,
        "VEL (km/s)":19.0,
        "REMARKS":"Eclipsing binary (partial)"
    },
    {
        "RANK":93,
        "PROPER NAME":"Menkar",
        "GREEK LETTER NAME":"Alpha Cet",
        "CLASS":"M1.5III",
        "DIST (LY)":220.0,
        "APP MAG":2.53,
        "ABS MAG":-1.62,
        "RAD VEL (km/s)":-26.0,
        "VEL (km/s)":37.0,
        "REMARKS":"Irregular variable"
    },
    {
        "RANK":56,
        "PROPER NAME":"Menkent",
        "GREEK LETTER NAME":"Theta Cen",
        "CLASS":"K0III",
        "DIST (LY)":61.0,
        "APP MAG":2.06,
        "ABS MAG":0.7,
        "RAD VEL (km/s)":1.3,
        "VEL (km/s)":65.0,
        "REMARKS":"Like Pollux; high velocity"
    },
    {
        "RANK":79,
        "PROPER NAME":"Merak",
        "GREEK LETTER NAME":"Beta UMa",
        "CLASS":"A1V",
        "DIST (LY)":79.0,
        "APP MAG":2.37,
        "ABS MAG":0.43,
        "RAD VEL (km/s)":-12.0,
        "VEL (km/s)":16.0,
        "REMARKS":"Vega system, circumstellar dust; Big Dipper; UMa cluster"
    },
    {
        "RANK":28,
        "PROPER NAME":"Miaplacidus",
        "GREEK LETTER NAME":"Beta Car",
        "CLASS":"A2IV",
        "DIST (LY)":111.0,
        "APP MAG":1.68,
        "ABS MAG":-1.98,
        "RAD VEL (km/s)":-5.0,
        "VEL (km/s)":31.0,
        "REMARKS":"With Atria, one of two brightest near SCP"
    },
    {
        "RANK":19,
        "PROPER NAME":"Mimosa",
        "GREEK LETTER NAME":"Beta Cru",
        "CLASS":"B0.5III",
        "DIST (LY)":280.0,
        "APP MAG":1.25,
        "ABS MAG":-3.41,
        "RAD VEL (km/s)":16.0,
        "VEL (km/s)":26.0,
        "REMARKS":"Beta Cep variable"
    },
    {
        "RANK":172,
        "PROPER NAME":"Minkar",
        "GREEK LETTER NAME":"Epsilon Crv",
        "CLASS":"K2.5III",
        "DIST (LY)":303.0,
        "APP MAG":3.0,
        "ABS MAG":-1.84,
        "RAD VEL (km/s)":4.9,
        "VEL (km/s)":32.0,
        "REMARKS":"Somewhat metal-rich"
    },
    {
        "RANK":67,
        "PROPER NAME":"Mintaka",
        "GREEK LETTER NAME":"Delta Ori",
        "CLASS":"B0III+O9V",
        "DIST (LY)":915.0,
        "APP MAG":2.23,
        "ABS MAG":-5.3,
        "RAD VEL (km/s)":16.0,
        "VEL (km/s)":16.0,
        "REMARKS":"Close binary; distant mag 6.5 class B2V companion"
    },
    {
        "RANK":57,
        "PROPER NAME":"Mirach",
        "GREEK LETTER NAME":"Beta And",
        "CLASS":"M0III",
        "DIST (LY)":200.0,
        "APP MAG":2.06,
        "ABS MAG":-1.87,
        "RAD VEL (km/s)":0.3,
        "VEL (km/s)":60.0,
        "REMARKS":"High velocity; distant faint companion"
    },
    {
        "RANK":35,
        "PROPER NAME":"Mirfak",
        "GREEK LETTER NAME":"Alpha Per",
        "CLASS":"F5Iab",
        "DIST (LY)":590.0,
        "APP MAG":1.79,
        "ABS MAG":-4.5,
        "RAD VEL (km/s)":-2.0,
        "VEL (km/s)":31.0,
        "REMARKS":"Alpha Persei cluster"
    },
    {
        "RANK":46,
        "PROPER NAME":"Mirzam",
        "GREEK LETTER NAME":"Beta CMa",
        "CLASS":"B1II-III",
        "DIST (LY)":500.0,
        "APP MAG":1.98,
        "ABS MAG":-3.94,
        "RAD VEL (km/s)":34.0,
        "VEL (km/s)":34.0,
        "REMARKS":"Beta Cep variable"
    },
    {
        "RANK":55,
        "PROPER NAME":"Mizar",
        "GREEK LETTER NAME":"Zeta UMa",
        "CLASS":"A2Vp+A7Vm",
        "DIST (LY)":78.0,
        "APP MAG":2.06,
        "ABS MAG":null,
        "RAD VEL (km/s)":-7.0,
        "VEL (km/s)":16.0,
        "REMARKS":"Double, A and B mags 2.27, 3.95; abs mags 0.37, 2.05; each again double; with Alcor, sextuple; peculiar abundances; Big Dipper; UMa cluster"
    },
    {
        "RANK":113,
        "PROPER NAME":"Mu Vel",
        "GREEK LETTER NAME":"Mu Vel",
        "CLASS":"G5III+G2V",
        "DIST (LY)":116.0,
        "APP MAG":2.69,
        "ABS MAG":-0.06,
        "RAD VEL (km/s)":6.2,
        "VEL (km/s)":15.0,
        "REMARKS":"Mags 2.8, 5.7, uncertain; Double, abs mags 0.1, 3.0; giant flare"
    },
    {
        "RANK":64,
        "PROPER NAME":"Muhlifain",
        "GREEK LETTER NAME":"Gamma Cen",
        "CLASS":"A1IV",
        "DIST (LY)":130.0,
        "APP MAG":2.17,
        "ABS MAG":null,
        "RAD VEL (km/s)":-5.5,
        "VEL (km/s)":36.0,
        "REMARKS":"Binary, identical components ave 0.94\", 84 yr period, mags 2.8, 2.9; abs mags -0.2, -0.1"
    },
    {
        "RANK":110,
        "PROPER NAME":"Muphrid",
        "GREEK LETTER NAME":"Eta Boo",
        "CLASS":"G0IV",
        "DIST (LY)":37.0,
        "APP MAG":2.68,
        "ABS MAG":2.41,
        "RAD VEL (km/s)":-0.1,
        "VEL (km/s)":20.0,
        "REMARKS":"Super metal-rich; hot corona"
    },
    {
        "RANK":124,
        "PROPER NAME":"Nair al Saif",
        "GREEK LETTER NAME":"Iota Ori",
        "CLASS":"O9III",
        "DIST (LY)":1300.0,
        "APP MAG":2.77,
        "ABS MAG":-5.6,
        "RAD VEL (km/s)":22.0,
        "VEL (km/s)":22.0,
        "REMARKS":"Odd spect. binary; origin of runaway stars Mu Col and AE Aur"
    },
    {
        "RANK":71,
        "PROPER NAME":"Naos",
        "GREEK LETTER NAME":"Zeta Pup",
        "CLASS":"O5Ia",
        "DIST (LY)":970.0,
        "APP MAG":2.25,
        "ABS MAG":-5.4,
        "RAD VEL (km/s)":-24.0,
        "VEL (km/s)":55.0,
        "REMARKS":"Runaway star from cluster Tr 10; rapid rotation"
    },
    {
        "RANK":139,
        "PROPER NAME":"Nihal",
        "GREEK LETTER NAME":"Beta Lep",
        "CLASS":"G5II",
        "DIST (LY)":159.0,
        "APP MAG":2.84,
        "ABS MAG":-0.6,
        "RAD VEL (km/s)":-14.0,
        "VEL (km/s)":24.0,
        "REMARKS":"Odd companion; chemically peculiar"
    },
    {
        "RANK":51,
        "PROPER NAME":"Nunki",
        "GREEK LETTER NAME":"Sigma Sgr",
        "CLASS":"B2.5V",
        "DIST (LY)":225.0,
        "APP MAG":2.02,
        "ABS MAG":-2.17,
        "RAD VEL (km/s)":-11.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Little Milk Dipper; Polaris probably a bit brighter"
    },
    {
        "RANK":44,
        "PROPER NAME":"Peacock",
        "GREEK LETTER NAME":"Alpha Pav",
        "CLASS":"B2IV",
        "DIST (LY)":183.0,
        "APP MAG":1.94,
        "ABS MAG":-1.81,
        "RAD VEL (km/s)":2.0,
        "VEL (km/s)":23.0,
        "REMARKS":"Close binary"
    },
    {
        "RANK":104,
        "PROPER NAME":"Phact",
        "GREEK LETTER NAME":"Alpha Col",
        "CLASS":"B7IVe",
        "DIST (LY)":270.0,
        "APP MAG":2.64,
        "ABS MAG":-1.94,
        "RAD VEL (km/s)":35.0,
        "VEL (km/s)":36.0,
        "REMARKS":"\"Be\" (emission) star"
    },
    {
        "RANK":85,
        "PROPER NAME":"Phecda",
        "GREEK LETTER NAME":"Gamma UMa",
        "CLASS":"A0Ve",
        "DIST (LY)":84.0,
        "APP MAG":2.44,
        "ABS MAG":0.39,
        "RAD VEL (km/s)":-13.0,
        "VEL (km/s)":18.0,
        "REMARKS":"Rapid rotator, Ae (emission) star; spect binary; Big Dipper; UMa cluster"
    },
    {
        "RANK":115,
        "PROPER NAME":"Pi Pup",
        "GREEK LETTER NAME":"Pi Pup",
        "CLASS":"K3Ib",
        "DIST (LY)":925.0,
        "APP MAG":2.7,
        "ABS MAG":-4.87,
        "RAD VEL (km/s)":16.0,
        "VEL (km/s)":23.0,
        "REMARKS":"In cluster Col 132; 0.3 mag interstellar abs."
    },
    {
        "RANK":150,
        "PROPER NAME":"Pi Sco",
        "GREEK LETTER NAME":"Pi Sco",
        "CLASS":"B1V+B2V",
        "DIST (LY)":520.0,
        "APP MAG":2.89,
        "ABS MAG":-3.38,
        "RAD VEL (km/s)":-3.0,
        "VEL (km/s)":19.0,
        "REMARKS":"Spectroscopic double; distance from luminosity; 1\/4 mag dust absorption"
    },
    {
        "RANK":50,
        "PROPER NAME":"Polaris",
        "GREEK LETTER NAME":"Alpha UMi",
        "CLASS":"F7Ib-II",
        "DIST (LY)":430.0,
        "APP MAG":2.02,
        "ABS MAG":-3.58,
        "RAD VEL (km/s)":-17.0,
        "VEL (km/s)":33.0,
        "REMARKS":"N. pole star; Cepheid variable; triple, F7 dwarf close, F3 distant"
    },
    {
        "RANK":17,
        "PROPER NAME":"Pollux",
        "GREEK LETTER NAME":"Beta Gem",
        "CLASS":"K0III",
        "DIST (LY)":34.0,
        "APP MAG":1.14,
        "ABS MAG":1.06,
        "RAD VEL (km/s)":3.0,
        "VEL (km/s)":31.0,
        "REMARKS":"Nearest K giant"
    },
    {
        "RANK":118,
        "PROPER NAME":"Porrima",
        "GREEK LETTER NAME":"Gamma Vir",
        "CLASS":"F0V+F0V",
        "DIST (LY)":38.0,
        "APP MAG":2.74,
        "ABS MAG":null,
        "RAD VEL (km/s)":-20.0,
        "VEL (km/s)":26.0,
        "REMARKS":"indentical double, mags 3.48, 3.53; abs mag 3.13, 3.18"
    },
    {
        "RANK":8,
        "PROPER NAME":"Procyon",
        "GREEK LETTER NAME":"Alpha CMi",
        "CLASS":"F5IV-V",
        "DIST (LY)":11.5,
        "APP MAG":0.34,
        "ABS MAG":2.61,
        "RAD VEL (km/s)":-3.0,
        "VEL (km/s)":21.0,
        "REMARKS":"White dwarf companion"
    },
    {
        "RANK":58,
        "PROPER NAME":"Rasalhague",
        "GREEK LETTER NAME":"Alpha Oph",
        "CLASS":"A5III",
        "DIST (LY)":47.0,
        "APP MAG":2.08,
        "ABS MAG":1.3,
        "RAD VEL (km/s)":13.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Faint close companion"
    },
    {
        "RANK":129,
        "PROPER NAME":"Rastaban",
        "GREEK LETTER NAME":"Beta Dra",
        "CLASS":"G2Ib-II",
        "DIST (LY)":362.0,
        "APP MAG":2.79,
        "ABS MAG":-2.43,
        "RAD VEL (km/s)":-20.0,
        "VEL (km/s)":22.0,
        "REMARKS":"Double; should be Cepheid but isn't."
    },
    {
        "RANK":33,
        "PROPER NAME":"Regor",
        "GREEK LETTER NAME":"Gamma-2 Vel",
        "CLASS":"WC8+O7.5e",
        "DIST (LY)":1200.0,
        "APP MAG":1.78,
        "ABS MAG":-6.3,
        "RAD VEL (km/s)":35.0,
        "VEL (km/s)":40.0,
        "REMARKS":"Wolf-Rayet, close binary; 0.3 mag dust absorption"
    },
    {
        "RANK":21,
        "PROPER NAME":"Regulus",
        "GREEK LETTER NAME":"Alpha Leo",
        "CLASS":"B7V",
        "DIST (LY)":79.0,
        "APP MAG":1.35,
        "ABS MAG":-0.58,
        "RAD VEL (km/s)":6.0,
        "VEL (km/s)":29.0,
        "REMARKS":"Binary red dwarf companion"
    },
    {
        "RANK":7,
        "PROPER NAME":"Rigel",
        "GREEK LETTER NAME":"Beta Ori",
        "CLASS":"B8Iab",
        "DIST (LY)":860.0,
        "APP MAG":0.12,
        "ABS MAG":-7.0,
        "RAD VEL (km/s)":21.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Nearby double companion; fainter one more distant"
    },
    {
        "RANK":3,
        "PROPER NAME":"Rigil Kentaurus A",
        "GREEK LETTER NAME":"Alpha Cen A",
        "CLASS":"G2V",
        "DIST (LY)":4.36,
        "APP MAG":-0.01,
        "ABS MAG":4.34,
        "RAD VEL (km/s)":-23.0,
        "VEL (km/s)":33.0,
        "REMARKS":"Companion Proxima Cen, 11.05 mag, M5.5V"
    },
    {
        "RANK":3,
        "PROPER NAME":"Rigil Kentaurus B",
        "GREEK LETTER NAME":"Alpha Cen B",
        "CLASS":"K1V",
        "DIST (LY)":4.36,
        "APP MAG":1.33,
        "ABS MAG":5.68,
        "RAD VEL (km/s)":-23.0,
        "VEL (km/s)":33.0,
        "REMARKS":"Combined magnitude -0.29; by itself would rank 21st"
    },
    {
        "RANK":109,
        "PROPER NAME":"Ruchbah",
        "GREEK LETTER NAME":"Delta Cas",
        "CLASS":"A5III-IV",
        "DIST (LY)":99.0,
        "APP MAG":2.68,
        "ABS MAG":0.26,
        "RAD VEL (km/s)":6.7,
        "VEL (km/s)":44.0,
        "REMARKS":"Eclipsing binary (partial)"
    },
    {
        "RANK":84,
        "PROPER NAME":"Sabik",
        "GREEK LETTER NAME":"Eta Oph",
        "CLASS":"A2V+A3V",
        "DIST (LY)":84.0,
        "APP MAG":2.43,
        "ABS MAG":null,
        "RAD VEL (km/s)":-0.9,
        "VEL (km/s)":13.0,
        "REMARKS":"Binary mag 3.0, 3.5; abs mag 0.9, 1.4"
    },
    {
        "RANK":163,
        "PROPER NAME":"Sadalmelik",
        "GREEK LETTER NAME":"Alpha Aqr",
        "CLASS":"G2Ib",
        "DIST (LY)":760.0,
        "APP MAG":2.96,
        "ABS MAG":-3.88,
        "RAD VEL (km/s)":7.5,
        "VEL (km/s)":24.0,
        "REMARKS":"Rare yellow supergiant; hybrid star"
    },
    {
        "RANK":155,
        "PROPER NAME":"Sadalsuud",
        "GREEK LETTER NAME":"Beta Aqr",
        "CLASS":"G0Ib",
        "DIST (LY)":610.0,
        "APP MAG":2.91,
        "ABS MAG":-3.46,
        "RAD VEL (km/s)":6.5,
        "VEL (km/s)":22.0,
        "REMARKS":"Rare mid-temperature supergiant; loosly related to Enif and Sadalmelik"
    },
    {
        "RANK":65,
        "PROPER NAME":"Sadr",
        "GREEK LETTER NAME":"Gamma Cyg",
        "CLASS":"F8Ib",
        "DIST (LY)":1500.0,
        "APP MAG":2.2,
        "ABS MAG":-6.8,
        "RAD VEL (km/s)":-8.0,
        "VEL (km/s)":9.0,
        "REMARKS":"Rich part of Milky Way; slightly variable"
    },
    {
        "RANK":53,
        "PROPER NAME":"Saiph",
        "GREEK LETTER NAME":"Kappa Ori",
        "CLASS":"B0.5Ia",
        "DIST (LY)":720.0,
        "APP MAG":2.06,
        "ABS MAG":-4.79,
        "RAD VEL (km/s)":21.0,
        "VEL (km/s)":21.0,
        "REMARKS":"Oddly low carbon"
    },
    {
        "RANK":83,
        "PROPER NAME":"Scheat",
        "GREEK LETTER NAME":"Beta Peg",
        "CLASS":"M2.5II-III",
        "DIST (LY)":200.0,
        "APP MAG":2.42,
        "ABS MAG":-1.51,
        "RAD VEL (km/s)":9.0,
        "VEL (km/s)":68.0,
        "REMARKS":"Irregular variable to bright 3rd mag"
    },
    {
        "RANK":25,
        "PROPER NAME":"Shaula",
        "GREEK LETTER NAME":"Lambda Sco",
        "CLASS":"B1.5IV+B2",
        "DIST (LY)":365.0,
        "APP MAG":1.63,
        "ABS MAG":-3.6,
        "RAD VEL (km/s)":-3.0,
        "VEL (km/s)":32.0,
        "REMARKS":"Triple: AB abs mags -3.2, -2.5; Ab forming star; Aa Beta Cep variable"
    },
    {
        "RANK":69,
        "PROPER NAME":"Shedar",
        "GREEK LETTER NAME":"Alpha Cas",
        "CLASS":"K0III",
        "DIST (LY)":230.0,
        "APP MAG":2.23,
        "ABS MAG":-2.0,
        "RAD VEL (km/s)":-4.0,
        "VEL (km/s)":20.0,
        "REMARKS":"Possible dimmings"
    },
    {
        "RANK":105,
        "PROPER NAME":"Sheratan",
        "GREEK LETTER NAME":"Beta Ari",
        "CLASS":"A5V",
        "DIST (LY)":60.0,
        "APP MAG":2.64,
        "ABS MAG":1.33,
        "RAD VEL (km/s)":-1.9,
        "VEL (km/s)":13.0,
        "REMARKS":"Spect binary"
    },
    {
        "RANK":1,
        "PROPER NAME":"Sirius",
        "GREEK LETTER NAME":"Alpha CMa",
        "CLASS":"A1V",
        "DIST (LY)":8.6,
        "APP MAG":-1.46,
        "ABS MAG":1.43,
        "RAD VEL (km/s)":-8.0,
        "VEL (km/s)":19.0,
        "REMARKS":"White dwarf companion"
    },
    {
        "RANK":16,
        "PROPER NAME":"Spica",
        "GREEK LETTER NAME":"Alpha Vir",
        "CLASS":"B1V+B4V",
        "DIST (LY)":250.0,
        "APP MAG":1.04,
        "ABS MAG":-3.38,
        "RAD VEL (km/s)":1.0,
        "VEL (km/s)":19.0,
        "REMARKS":"Close binary; 0.03 mag variation from tidal oblateness"
    },
    {
        "RANK":66,
        "PROPER NAME":"Suhail",
        "GREEK LETTER NAME":"Lambda Vel",
        "CLASS":"K4Ib-II",
        "DIST (LY)":575.0,
        "APP MAG":2.21,
        "ABS MAG":-4.02,
        "RAD VEL (km/s)":18.0,
        "VEL (km/s)":29.0,
        "REMARKS":"High velocity; irregular variable"
    },
    {
        "RANK":117,
        "PROPER NAME":"Tarazed",
        "GREEK LETTER NAME":"Gamma Aql",
        "CLASS":"K3II",
        "DIST (LY)":460.0,
        "APP MAG":2.72,
        "ABS MAG":-3.03,
        "RAD VEL (km/s)":-2.1,
        "VEL (km/s)":11.0,
        "REMARKS":"X-ray hybrid star"
    },
    {
        "RANK":157,
        "PROPER NAME":"Tau Pup",
        "GREEK LETTER NAME":"Tau Pup",
        "CLASS":"K1III",
        "DIST (LY)":182.0,
        "APP MAG":2.93,
        "ABS MAG":-0.8,
        "RAD VEL (km/s)":36.0,
        "VEL (km/s)":42.0,
        "REMARKS":"Spectroscopic double, 2.9-yr period"
    },
    {
        "RANK":148,
        "PROPER NAME":"Tejat",
        "GREEK LETTER NAME":"Mu Gem",
        "CLASS":"M3III",
        "DIST (LY)":232.0,
        "APP MAG":2.88,
        "ABS MAG":-1.38,
        "RAD VEL (km/s)":55.0,
        "VEL (km/s)":69.0,
        "REMARKS":"Variable by 25%; high velocity"
    },
    {
        "RANK":103,
        "PROPER NAME":"Theta Aur",
        "GREEK LETTER NAME":"Theta Aur",
        "CLASS":"A0pSi",
        "DIST (LY)":173.0,
        "APP MAG":2.62,
        "ABS MAG":-1.01,
        "RAD VEL (km/s)":30.0,
        "VEL (km/s)":36.0,
        "REMARKS":"Alpha-2 CVnmagnetic star; Binary with solar companion"
    },
    {
        "RANK":123,
        "PROPER NAME":"Theta Car",
        "GREEK LETTER NAME":"Theta Car",
        "CLASS":"B0Vp",
        "DIST (LY)":440.0,
        "APP MAG":2.76,
        "ABS MAG":3.11,
        "RAD VEL (km/s)":24.0,
        "VEL (km/s)":28.0,
        "REMARKS":"Silicon star; brightest blue straggler"
    },
    {
        "RANK":133,
        "PROPER NAME":"Tureis",
        "GREEK LETTER NAME":"Rho Pup",
        "CLASS":"F6II",
        "DIST (LY)":63.0,
        "APP MAG":2.81,
        "ABS MAG":1.39,
        "RAD VEL (km/s)":46.0,
        "VEL (km/s)":47.0,
        "REMARKS":"Brightest Delta Sct star"
    },
    {
        "RANK":107,
        "PROPER NAME":"Unukalhai",
        "GREEK LETTER NAME":"Alpha Ser",
        "CLASS":"K2III",
        "DIST (LY)":73.0,
        "APP MAG":2.65,
        "ABS MAG":0.89,
        "RAD VEL (km/s)":0.7,
        "VEL (km/s)":15.0,
        "REMARKS":"X-ray emitter; strong carbon"
    },
    {
        "RANK":161,
        "PROPER NAME":"Upsilon Car",
        "GREEK LETTER NAME":"Upsilon Car",
        "CLASS":"A6Ib+B3-4IV",
        "DIST (LY)":1250.0,
        "APP MAG":2.95,
        "ABS MAG":null,
        "RAD VEL (km/s)":14.0,
        "VEL (km/s)":53.0,
        "REMARKS":"Binary, dist. from spectral classes; mags 3.02, 6.03; abs mags -5.0, -2.5; 0.35 mag dust abs."
    },
    {
        "RANK":5,
        "PROPER NAME":"Vega",
        "GREEK LETTER NAME":"Alpha Lyr",
        "CLASS":"A0V",
        "DIST (LY)":25.0,
        "APP MAG":0.03,
        "ABS MAG":0.6,
        "RAD VEL (km/s)":-14.0,
        "VEL (km/s)":19.0,
        "REMARKS":"Dusty circumstellar disk"
    },
    {
        "RANK":138,
        "PROPER NAME":"Vindemiatrix",
        "GREEK LETTER NAME":"Epsilon Vir",
        "CLASS":"G8III",
        "DIST (LY)":102.0,
        "APP MAG":2.83,
        "ABS MAG":0.35,
        "RAD VEL (km/s)":-14.0,
        "VEL (km/s)":43.0,
        "REMARKS":"Strong X-ray source"
    },
    {
        "RANK":36,
        "PROPER NAME":"Wezen",
        "GREEK LETTER NAME":"Delta CMa",
        "CLASS":"F8Iab",
        "DIST (LY)":1800.0,
        "APP MAG":1.84,
        "ABS MAG":-6.9,
        "RAD VEL (km/s)":34.0,
        "VEL (km/s)":36.0,
        "REMARKS":"Rare yellow supergiant"
    },
    {
        "RANK":120,
        "PROPER NAME":"Yed Prior",
        "GREEK LETTER NAME":"Delta Oph",
        "CLASS":"M0.5III",
        "DIST (LY)":170.0,
        "APP MAG":2.74,
        "ABS MAG":-0.85,
        "RAD VEL (km/s)":-20.0,
        "VEL (km/s)":42.0,
        "REMARKS":"Iron-rich; non-variable standard"
    },
    {
        "RANK":162,
        "PROPER NAME":"Zaurak",
        "GREEK LETTER NAME":"Gamma Eri",
        "CLASS":"M0.5III",
        "DIST (LY)":221.0,
        "APP MAG":2.95,
        "ABS MAG":-1.21,
        "RAD VEL (km/s)":62.0,
        "VEL (km/s)":74.0,
        "REMARKS":"Slightly variable; high velocity"
    },
    {
        "RANK":94,
        "PROPER NAME":"Zeta Cen",
        "GREEK LETTER NAME":"Zeta Cen",
        "CLASS":"B2.5IV",
        "DIST (LY)":385.0,
        "APP MAG":2.55,
        "ABS MAG":-2.84,
        "RAD VEL (km/s)":6.5,
        "VEL (km/s)":41.0,
        "REMARKS":"Spect binary"
    },
    {
        "RANK":134,
        "PROPER NAME":"Zeta Her",
        "GREEK LETTER NAME":"Zeta Her",
        "CLASS":"G0IV+G7V",
        "DIST (LY)":35.0,
        "APP MAG":2.81,
        "ABS MAG":2.64,
        "RAD VEL (km/s)":70.0,
        "VEL (km/s)":76.0,
        "REMARKS":"Double, mags 2.90, 5.53, abs mags 2.73, 5.36; high velocity"
    },
    {
        "RANK":95,
        "PROPER NAME":"Zeta Oph",
        "GREEK LETTER NAME":"Zeta Oph",
        "CLASS":"O9.5V",
        "DIST (LY)":460.0,
        "APP MAG":2.56,
        "ABS MAG":-4.27,
        "RAD VEL (km/s)":-15.0,
        "VEL (km/s)":24.0,
        "REMARKS":"1.1 mag dust extinction; runaway star"
    },
    {
        "RANK":140,
        "PROPER NAME":"Zeta Per",
        "GREEK LETTER NAME":"Zeta Per",
        "CLASS":"B1Iab",
        "DIST (LY)":980.0,
        "APP MAG":2.85,
        "ABS MAG":-5.6,
        "RAD VEL (km/s)":20.0,
        "VEL (km/s)":25.0,
        "REMARKS":"1.06 mag interstellar abs; two companions"
    },
    {
        "RANK":169,
        "PROPER NAME":"Zeta Tau",
        "GREEK LETTER NAME":"Zeta Tau",
        "CLASS":"B2IIIpe",
        "DIST (LY)":420.0,
        "APP MAG":3.0,
        "ABS MAG":-2.53,
        "RAD VEL (km/s)":20.0,
        "VEL (km/s)":22.0,
        "REMARKS":"Classic B-emission star"
    },
    {
        "RANK":96,
        "PROPER NAME":"Zosma",
        "GREEK LETTER NAME":"Delta Leo",
        "CLASS":"A4V",
        "DIST (LY)":58.0,
        "APP MAG":2.56,
        "ABS MAG":1.28,
        "RAD VEL (km/s)":-20.0,
        "VEL (km/s)":26.0,
        "REMARKS":"Delta Sct variable"
    },
    {
        "RANK":122,
        "PROPER NAME":"Zubenelgenubi",
        "GREEK LETTER NAME":"Alpha-2 Lib",
        "CLASS":"A3IV",
        "DIST (LY)":77.0,
        "APP MAG":2.75,
        "ABS MAG":0.88,
        "RAD VEL (km/s)":-10.0,
        "VEL (km/s)":17.0,
        "REMARKS":"Double; Alpha-1 5th mag F4 dwarf naked-eye companion"
    },
    {
        "RANK":101,
        "PROPER NAME":"Zubeneschamali",
        "GREEK LETTER NAME":"Beta Lib",
        "CLASS":"B8V",
        "DIST (LY)":160.0,
        "APP MAG":2.61,
        "ABS MAG":-0.84,
        "RAD VEL (km/s)":-35.0,
        "VEL (km/s)":42.0,
        "REMARKS":"Traditionally reputed to be green."
    }
]

//Create list of stars
var select = document.getElementById("selectStar");

for(var i = 0; i < stars.length; i++) {
    var opt = stars[i]["PROPER NAME"];
    var el = document.createElement("option");
    el.textContent = opt;
    el.value = i;
    select.appendChild(el);
}

function star_pick(star_list){
    var x =document.getElementById("selectStar").value;
    document.getElementById("starResult").innerHTML = "You selected the star: " + star_list[x]["PROPER NAME"] + "<br>";
}


var select_property = document.getElementById("selectProperty");

for(let j in stars[1]) {
    var opt1 = j;
    var el1 = document.createElement("option");
    el1.textContent = opt1;
    el1.value = opt1;
    select_property.appendChild(el1);
}


function property_pick(star_list){
    var x =document.getElementById("selectStar").value;
    var y =document.getElementById("selectProperty").value;
    document.getElementById("starProperty").innerHTML = "You selected the star: " + star_list[x]["PROPER NAME"] + "<br>" + "and the star property " + y + "<br>" +
"which has a value of " + star_list[x][y] + "<br>";
}

/*
function json_parse(star_data){
    for(i=0;i<star_data.length;i++)
        {
           console.log(star_data[i]["GREEK LETTER NAME"]);
        }
    }

json_parse(stars);
*/


/*
function json_parse(star_data){
    for(i=0;i<star_data.length;i++)
        {
           console.log(star_data[i]["GREEK LETTER NAME"]);
        }
    }

json_parse(stars);
*/
